[build]
  command = "npm install"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"]

[[redirects]]
  from = "/auth/google"
  to = "/.netlify/functions/auth-google"
  status = 200

[[redirects]]
  from = "/api/auth/google/callback"
  to = "/.netlify/functions/auth-google-callback"
  status = 200

[[redirects]]
  from = "/api/auth/token"
  to = "/.netlify/functions/auth-token"
  status = 200

[[redirects]]
  from = "/api/watchlist"
  to = "/.netlify/functions/watchlist"
  status = 200

[[redirects]]
  from = "/api/watched"
  to = "/.netlify/functions/watched"
  status = 200